#!/usr/bin/env bash
#display time after every 59 min

time=0

while [ $time -lt 13 ]
do
echo "Hour: $time"
time=$((time+1))

minute=1

while [ $minute -lt 60 ]
do
echo $minute
minute=$((minute+1))

done
done
