#!/usr/bin/env bash
#displays info about a school file

my_file="school"

if [ -e "$my_file" ]
then
echo "$my_file file exists"
if [ ! -s "$my_file" ]
then
echo "$my_file file is empty"
else
echo "$my_file file is not empty"
fi
if [ -f "$my_file" ]
then
echo "$my_file is a regular file"
fi
else
echo "$my_file file does not exist"
fi
